version: '3.8'
services:
  mongodb:
    image: 'mongo'
    ports:
      - 27018:27027
    volumes:
      - data:/data/db
    #environment:
      # MONGO_INITDB_ROOT_USERNAME:ayush
      # MONGO_INITDB_ROOT_PASSWORD:ayush
    # env_file:
    #   - ./env/mongo.env
    # networks:
    #   - mern-app
  
  
  backend:
    build: ./server/api
    ports:
      - 8080:8080
    volumes:
      - ./server/api:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./env/api.env
    # networks:
    #   - mern-app
    depends_on:
      - mongodb

  frontend:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    # networks:
    #   - mern-app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data: